# Generated by Django 4.0.5 on 2022-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDatos',
            fields=[
                ('idRut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
            ],
        ),
    ]
