# Generated by Django 4.0.5 on 2022-06-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotienda',
            name='user',
        ),
    ]
