# Generated by Django 4.0.5 on 2022-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usuariotienda_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProd', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', models.ImageField(upload_to='core/static/imgProd')),
            ],
        ),
    ]
