# Generated by Django 4.0.5 on 2022-06-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='UsuarioTienda',
        ),
    ]
