# Generated by Django 4.0.5 on 2022-06-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='UsuarioTienda',
        ),
    ]
